use_frameworks!

target 'FKLModuleManager_Example' do
  pod 'FKLModuleManager', :path => '../'

  target 'FKLModuleManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
